apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  namespace: retail 
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: retail-store
    environment: dev
data:
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: "in-memory"
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: "http://orders:8080"