sonar.sources=application
sonar.sourceEncoding=UTF-8

sonar.java.binaries=application/ui/target/classes,application/cart/target/classes,application/orders/target/classes
sonar.tests=application/ui/src/test,application/cart/src/test,application/orders/src/test
sonar.test.exclusions=**/target/**
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.yarn/**,**/generated-sources/**,**/src/test/**
sonar.coverage.jacoco.xmlReportPaths=application/ui/target/site/jacoco/jacoco.xml,application/cart/target/site/jacoco/jacoco.xml,application/orders/target/site/jacoco/jacoco.xml
