sonar.sources=application
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.yarn/**,**/generated-sources/**

sonar.java.binaries=application/ui/target/classes,application/cart/target/classes,application/orders/target/classes