{{- range $serviceAccount, $service := .Values.services }}
{{- if $service.enabled }}
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount }}
  namespace: {{ $.Release.Namespace | quote}}
  labels:
    {{- include "retail.labels" (dict "serviceName" $serviceAccount "root" $) | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
