imageRegistry: "147723036683.dkr.ecr.us-east-1.amazonaws.com"

services:
  ui:
    enabled: true
    replicas: 1
    image:
      repository: "retail-ui"
      tag: "cfc435e2a26d0b8c3aae16f156f68272a982dec9-37771994371-1"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    config:
      RETAIL_UI_ENDPOINTS_CATALOG: "http://catalog:8080"
      RETAIL_UI_ENDPOINTS_CARTS: "http://cart:8080"
      RETAIL_UI_ENDPOINTS_ORDERS: "http://orders:8080"
      RETAIL_UI_ENDPOINTS_CHECKOUT: "http://checkout:8080"

  catalog:
    enabled: true
    replicas: 1
    image:
      repository: "retail-catalog"
      tag: "cfc435e2a26d0b8c3aae16f156f68272a982dec9-37771994371-1"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  cart:
    enabled: true
    replicas: 1
    image:
      repository: "retail-cart"
      tag: "cfc435e2a26d0b8c3aae16f156f68272a982dec9-37771994371-1"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  orders:
    enabled: true
    replicas: 1
    image:
      repository: "retail-orders"
      tag: "cfc435e2a26d0b8c3aae16f156f68272a982dec9-37771994371-1"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  checkout:
    enabled: true
    replicas: 1
    image:
      repository: "retail-checkout"
      tag: "cfc435e2a26d0b8c3aae16f156f68272a982dec9-37771994371-1"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    config:
      RETAIL_CHECKOUT_ENDPOINTS_ORDERS: "http://orders:8080"

ingress:
  enabled: true
  securityGroup: "sg-0d34df973e11988c7"
  tags: environment=dev,project=retail-platform

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]