clusterName: "retail-platform-dev"
region: "us-east-1"
vpcId: "vpc-03ee4579ab34afda6"

replicaCount: 2

serviceAccount:
  create: false
  name: aws-load-balancer-controller

defaultTags:
  environment: dev
  project: retail-platform