clusterName: "retail-platform-dev"
region: "us-east-1"
vpcId: "vpc-0db6127af3d46972d"

replicaCount: 2

serviceAccount:
  create: false
  name: aws-load-balancer-controller

defaultTags:
  environment: dev
  project: retail-platform