apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: retail
  labels:
    app.kubernetes.io/part-of: retail-store
    app.kubernetes.io/component: application
spec:
  selector:
    app.kubernetes.io/name: checkout
  ports:
  - port: 8080
    name: http
    targetPort: http