prometheus:
  ingress:
    enabled: false
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

grafana:
  enabled: true
  ingress:
    enabled: false
  service:
    type: ClusterIP

alertmanager:
  enabled: true