apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
  namespace: retail
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: restail-store
    environment: dev
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  namespace: retail 
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/part-of: retail-store
    environment: dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders
  namespace: retail 
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: retail-store
    environment: dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout
  namespace: retail 
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: retail-store
    environment: dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui
  namespace: retail 
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: retail-store
    environment: dev