apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retail
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: retail-store
    app.kubernetes.io/component: application
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
        app.kubernetes.io/part-of: retail-store
        app.kubernetes.io/component: application
    spec:
      serviceAccountName: ui
      containers:
      - name: ui
        image: 147723036683.dkr.ecr.us-east-1.amazonaws.com/retail-ui:a6285f6d3a33ea41cb0de01edbbe2bcee6efcfd1-36147074794-1
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: ui-config
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - name: http
          containerPort: 8080
