apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: retail
  namespace: argocd
spec:
  description: Retail application workloads for the dev environment

  sourceRepos:
    - https://github.com/ahmedmohsen5/01-retail-production-platform.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: retail

  clusterResourceWhitelist: []

  namespaceResourceWhitelist:
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: Ingress
